// Dados reais dos países das Olimpíadas de 2024
const paises = [
    {
        pais: "Estados Unidos",
        ouro: 40,
        prata: 44,
        bronze: 42,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/USA.png",
    },
    {
        pais: "China",
        ouro: 40,
        prata: 27,
        bronze: 24,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CHN.png",
    },
    {
        pais: "Japão",
        ouro: 20,
        prata: 12,
        bronze: 13,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/JPN.png",
    },
    {
        pais: "Austrália",
        ouro: 18,
        prata: 19,
        bronze: 16,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/AUS.png",
    },
    {
        pais: "França",
        ouro: 16,
        prata: 26,
        bronze: 22,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/FRA.png",
    },
    {
        pais: "Países Baixos",
        ouro: 15,
        prata: 7,
        bronze: 12,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/NED.png",
    },
    {
        pais: "Grã-Bretanha",
        ouro: 14,
        prata: 22,
        bronze: 29,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/GBR.png",
    },
    {
        pais: "Coréia do Sul",
        ouro: 13,
        prata: 9,
        bronze: 10,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/KOR.png",
    },
    {
        pais: "Itália",
        ouro: 12,
        prata: 13,
        bronze: 15,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ITA.png",
    },
    {
        pais: "Alemanha",
        ouro: 12,
        prata: 13,
        bronze: 8,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/GER.png",
    },
    {
        pais: "Nova Zelândia",
        ouro: 10,
        prata: 7,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/NZL.png",
    },
    {
        pais: "Canadá",
        ouro: 9,
        prata: 7,
        bronze: 11,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CAN.png",
    },
    {
        pais: "Uzbequistão",
        ouro: 8,
        prata: 2,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/UZB.png",
    },
    {
        pais: "Hungria",
        ouro: 6,
        prata: 7,
        bronze: 6,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/HUN.png",
    },
    {
        pais: "Espanha",
        ouro: 5,
        prata: 4,
        bronze: 9,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ESP.png",
    },
    {
        pais: "Suécia",
        ouro: 4,
        prata: 4,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/SWE.png",
    },
    {
        pais: "Quênia",
        ouro: 4,
        prata: 2,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/KEN.png",
    },
    {
        pais: "Noruega",
        ouro: 4,
        prata: 1,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/NOR.png",
    },
    {
        pais: "Irlanda",
        ouro: 4,
        prata: 0,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/IRL.png",
    },
    {
        pais: "Brasil",
        ouro: 3,
        prata: 7,
        bronze: 10,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/BRA.png",
    },
    {
        pais: "Irã",
        ouro: 3,
        prata: 6,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/IRI.png",
    },
    {
        pais: "Ucrânia",
        ouro: 3,
        prata: 5,
        bronze: 4,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/UKR.png",
    },
    {
        pais: "Romênia",
        ouro: 3,
        prata: 4,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ROU.png",
    },
    {
        pais: "Geórgia",
        ouro: 3,
        prata: 3,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/GEO.png",
    },
    {
        pais: "Bélgica",
        ouro: 3,
        prata: 1,
        bronze: 6,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/BEL.png",
    },
    {
        pais: "Bulgária",
        ouro: 3,
        prata: 1,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/BUL.png",
    },
    {
        pais: "Sérvia",
        ouro: 3,
        prata: 1,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/SRB.png",
    },
    {
        pais: "Tchéquia",
        ouro: 3,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CZE.png",
    },
    {
        pais: "Dinamarca",
        ouro: 2,
        prata: 2,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/DEN.png",
    },
    {
        pais: "Azerbaijão",
        ouro: 2,
        prata: 2,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/AZE.png",
    },
    {
        pais: "Croácia",
        ouro: 2,
        prata: 2,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CRO.png",
    },
    {
        pais: "Cuba",
        ouro: 2,
        prata: 1,
        bronze: 6,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CUB.png",
    },
    {
        pais: "Bahrein",
        ouro: 2,
        prata: 1,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/BRN.png",
    },
    {
        pais: "Eslovênia",
        ouro: 2,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/SLO.png",
    },
    {
        pais: "Taipé Chinês",
        ouro: 2,
        prata: 0,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/TPE.png",
    },
    {
        pais: "Áustria",
        ouro: 2,
        prata: 0,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/AUT.png",
    },
    {
        pais: "Hong Kong",
        ouro: 2,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/HKG.png",
    },
    {
        pais: "Filipinas",
        ouro: 2,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/PHI.png",
    },
    {
        pais: "Argélia",
        ouro: 2,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ALG.png",
    },
    {
        pais: "Indonésia",
        ouro: 2,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/INA.png",
    },
    {
        pais: "Israel",
        ouro: 1,
        prata: 5,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ISR.png",
    },
    {
        pais: "Polônia",
        ouro: 1,
        prata: 4,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/POL.png",
    },
    {
        pais: "Cazaquistão",
        ouro: 1,
        prata: 3,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/KAZ.png",
    },
    {
        pais: "Jamaica",
        ouro: 1,
        prata: 3,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/JAM.png",
    },
    {
        pais: "África do Sul",
        ouro: 1,
        prata: 3,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/RSA.png",
    },
    {
        pais: "Tailândia",
        ouro: 1,
        prata: 3,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/THA.png",
    },
    {
        pais: "Etiópia",
        ouro: 1,
        prata: 3,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ETH.png",
    },
    {
        pais: "Suíça",
        ouro: 1,
        prata: 2,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/SUI.png",
    },
    {
        pais: "Equador",
        ouro: 1,
        prata: 2,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ECU.png",
    },
    {
        pais: "Portugal",
        ouro: 1,
        prata: 2,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/POR.png",
    },
    {
        pais: "Grécia",
        ouro: 1,
        prata: 1,
        bronze: 6,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/GRE.png",
    },
    {
        pais: "Argentina",
        ouro: 1,
        prata: 1,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ARG.png",
    },
    {
        pais: "Egito",
        ouro: 1,
        prata: 1,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/EGY.png",
    },
    {
        pais: "Tunísia",
        ouro: 1,
        prata: 1,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/TUN.png",
    },
    {
        pais: "Botsuana",
        ouro: 1,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/BOT.png",
    },
    {
        pais: "Chile",
        ouro: 1,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CHI.png",
    },
    {
        pais: "Santa Lúcia",
        ouro: 1,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/LCA.png",
    },
    {
        pais: "Uganda",
        ouro: 1,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/UGA.png",
    },
    {
        pais: "República Dominicana",
        ouro: 1,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/DOM.png",
    },
    {
        pais: "Guatemala",
        ouro: 1,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/GUA.png",
    },
    {
        pais: "Marrocos",
        ouro: 1,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/MAR.png",
    },
    {
        pais: "Dominica",
        ouro: 1,
        prata: 0,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/DMA.png",
    },
    {
        pais: "Paquistão",
        ouro: 1,
        prata: 0,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/PAK.png",
    },
    {
        pais: "Turquia",
        ouro: 0,
        prata: 3,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/TUR.png",
    },
    {
        pais: "México",
        ouro: 0,
        prata: 3,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/MEX.png",
    },
    {
        pais: "Armênia",
        ouro: 0,
        prata: 3,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ARM.png",
    },
    {
        pais: "Colômbia",
        ouro: 0,
        prata: 3,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/COL.png",
    },
    {
        pais: "Quirguistão",
        ouro: 0,
        prata: 2,
        bronze: 4,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/KGZ.png",
    },
    {
        pais: "Coreia do Norte",
        ouro: 0,
        prata: 2,
        bronze: 4,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/PRK.png",
    },
    {
        pais: "Lituânia",
        ouro: 0,
        prata: 2,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/LTU.png",
    },
    {
        pais: "Índia",
        ouro: 0,
        prata: 1,
        bronze: 5,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/IND.png",
    },
    {
        pais: "República da Maldávia",
        ouro: 0,
        prata: 1,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/MDA.png",
    },
    {
        pais: "Kosovo",
        ouro: 0,
        prata: 1,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/KOS.png",
    },
    {
        pais: "Chipre",
        ouro: 0,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CYP.png",
    },
    {
        pais: "Fiji",
        ouro: 0,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/FIJ.png",
    },
    {
        pais: "Jordânia",
        ouro: 0,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/JOR.png",
    },
    {
        pais: "Mongólia",
        ouro: 0,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/MGL.png",
    },
    {
        pais: "Panamá",
        ouro: 0,
        prata: 1,
        bronze: 0,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/PAN.png",
    },
    {
        pais: "Tajiquistão",
        ouro: 0,
        prata: 0,
        bronze: 3,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/TJK.png",
    },
    {
        pais: "Albânia",
        ouro: 0,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ALB.png",
    },
    {
        pais: "Granada",
        ouro: 0,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/GRN.png",
    },
    {
        pais: "Malásia",
        ouro: 0,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/MAS.png",
    },
    {
        pais: "Porto Rico",
        ouro: 0,
        prata: 0,
        bronze: 2,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/PUR.png",
    },
    {
        pais: "Costa do Marfim",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CIV.png",
    },
    {
        pais: "Cabo Verde",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/CPV.png",
    },
    {
        pais: "Equipe Olímpica de Refugiados",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/EOR.png",
    },
    {
        pais: "Peru",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/PER.png",
    },
    {
        pais: "Catar",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/QAT.png",
    },
    {
        pais: "Singapura",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/SGP.png",
    },
    {
        pais: "Eslováquia",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/SVK.png",
    },
    {
        pais: "Zâmbia",
        ouro: 0,
        prata: 0,
        bronze: 1,
        url: "https://gstatic.olympics.com/s1/t_original/static/noc/oly/3x2/180x120/ZAM.png",
    }
];